kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80   # Map port 80 to the host
    hostPort: 80        # Use port 80 on your local machine
    protocol: TCP
  - containerPort: 443  # Map port 443 to the host
    hostPort: 443       # Use port 443 on your local machine
    protocol: TCP
